### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by ArsenShnurkov** [KindDragon/ICSharpCode.TextEditor#1]
Hi, i want to package this project for gentoo.

I want you to put the history and current status into readme (do you accept patches)

original code in SharpDevelop distribution is available here for download:
http://www.icsharpcode.net/OpenSource/SD/Download
archive's doc/license.txt clearly says LGPL 2.1, for files of TextEditor (beside others)

<br /><br />
I found several more forks on github (but didn't analysed them):

https://github.com/StefH/ICSharpCode.TextEditorEx
Extended version based on ICSharpCode.TextEditor which support Search/Replace and Goto 
GPLv2

https://github.com/nano-byte/ICSharpCode.TextEditor
text editor used in SharpDevelop 3 with some custom patches 

https://github.com/cepthomas/ICSharpCode.TextEditor.V4
An evolution of the old WinForm text editor. (repository owner moved to Avalon and put that project on hold)
LGPL-2.1

https://github.com/electroly/ospa-texteditor
OSPA's fork of ICSharpCode.TextEditor 
propiertary - https://github.com/electroly/ospa-texteditor/blob/master/copyright.txt

**Comment by ArsenShnurkov** [comment]
Found another WinForms editor control (MIT License) - https://github.com/jacobslusser/ScintillaNET

**Comment by ArsenShnurkov** [comment]
For now I have the following idea - If Issues are not disabled, then owner wants to be a maintainer for the fork tree

**Comment by ArsenShnurkov** [comment]
here is the ebuild
https://github.com/ArsenShnurkov/dotnet/commit/a1f3d7c79bb279fe58494b8a73c01bb593ed484b

**Comment by KindDragon** [comment]
It's just internal fork for GitExtension. We plan move to ScintillaNET someday, because it's works on Linux.

**Comment by ArsenShnurkov** [comment]
this one is also works on linux (after minimal patching may be)

**Comment by KindDragon** [comment]
Maybe then fork for https://github.com/cepthomas/ICSharpCode.TextEditor.V4
They provide some improvments
